# Uncomment the next line to define a global platform for your project
#source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
use_frameworks!


target 'ThirdApp' do
  # Comment the next line if you don't want to use dynamic frameworks

  # Pods for ThirdApp
#pod 'ChangeTextView', :path => '../changeTextView/changeTextView'

pod 'ChangeTextView'

#, :git => 'https://github.com/bakenova/changeTextView.git'
end
